# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Final.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('Qt5Agg')
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg, NavigationToolbar2QT as Navi
from matplotlib.figure import Figure
import seaborn as sns
import pandas as pd
import sip # can be installed : pip install si

class MatplotlibCanvas(FigureCanvasQTAgg):
	def __init__(self,parent=None, dpi = 100):
		fig = Figure(dpi = dpi)
		self.axes = fig.add_subplot(111)
		super(MatplotlibCanvas,self).__init__(fig)
		fig.tight_layout()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1619, 840)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -30, 1791, 881))
        self.label.setStyleSheet("background-image: url(:/newPrefix/bg.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 0, 781, 101))
        self.label_3.setStyleSheet("/*font: 75 30pt \"MS Shell Dlg 2\";*/\n"
"color: rgb(255, 255, 255);\n"
"font: 75 italic 33pt \"Times New Roman\";\n"
"font: color-white;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1390, 20, 171, 111))
        self.label_2.setStyleSheet("image: url(:/logo/logo.png);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-6, -5, 201, 821))
        self.label_4.setStyleSheet("background-color: rgb(9, 34, 62);\n"
"background-color: rgb(22, 46, 82);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 50, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 120, 111, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1250, 150, 351, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(269, 99, 981, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1619, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_CSV = QtWidgets.QAction(MainWindow)
        self.actionOpen_CSV.setObjectName("actionOpen_CSV")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen_CSV)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
                ##### 
        
        self.filename = ''
        self.canv = MatplotlibCanvas(self)
        self.df = []
		
        self.toolbar = Navi(self.canv,self.centralwidget)
        self.horizontalLayout.addWidget(self.toolbar)
        
        self.themes = ['bmh', 'classic', 'dark_background', 'fast', 
        'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn-bright',
        'seaborn-colorblind', 'seaborn-dark-palette', 'seaborn-dark', 
        'seaborn-darkgrid', 'seaborn-deep', 'seaborn-muted', 'seaborn-notebook',
        'seaborn-paper', 'seaborn-pastel', 'seaborn-poster', 'seaborn-talk',
        'seaborn-ticks', 'seaborn-white', 'seaborn-whitegrid', 'seaborn',
        'Solarize_Light2', 'tableau-colorblind10']
         
        self.pushButton.clicked.connect(self.getFile)
        self.pushButton_4.clicked.connect(MainWindow.close)
        self.actionExit.triggered.connect(MainWindow.close)
        self.actionOpen_CSV.triggered.connect(self.getFile)
        
    def Update(self, value):
        print("Value from Combo Box:", value)
        plt.clf()
        plt.style.use(value)
        try:
            self.horizontalLayout.removeWidget(self.toolbar)
            self.verticalLayout.removeWidget(self.canv)

            sip.delete(self.toolbar)
            sip.delete(self.canv)
            self.toolbar = None
            self.canv = None
            #self.verticalLayout.removeItem(self.spacerItem1)
        except Exception as e:
            print(e)
            pass
        self.canv = MatplotlibCanvas(self)
        self.toolbar = Navi(self.canv, self.centralwidget)

        self.horizontalLayout.addWidget(self.toolbar)
        self.verticalLayout.addWidget(self.canv)

        self.canv.figure.clf()  # clear the figure

        # create four subplots
        ax1 = self.canv.figure.add_subplot(221)
        ax2 = self.canv.figure.add_subplot(222)
        ax3 = self.canv.figure.add_subplot(223)
        ax4 = self.canv.figure.add_subplot(224)

        # plot data on the first subplot
        ax1.plot(self.df)
        ax1.set_xlabel('X axis')
        ax1.set_ylabel('Columns')
        ax1.set_title('Line Plot')
        legend = ax1.legend(self.df,fontsize="8")
        legend.set_draggable(True)

        # plot data on the second subplot
        x = [x for x in range(len(self.df.iloc[:,0]))]
        ax2.scatter(x,self.df.iloc[:,0])
        ax2.set_xlabel('X axis')
        ax2.set_ylabel(self.df.columns[0])
        ax2.set_title('Scatter Plot')
        legend = ax2.legend([self.df.columns[0]])
        legend.set_draggable(True)

        # plot data on the third subplot
        y = [x for x in range(len(self.df.iloc[:,9]))]
        ax3.bar(self.df.iloc[:,9],self.df.iloc[:,0])
        ax3.set_xlabel(self.df.columns[9])
        ax3.set_ylabel(self.df.columns[0])
        ax3.set_title('Bar Plot')
        legend = ax3.legend([self.df.columns[9]])
        legend.set_draggable(True)

        # plot data on the fourth subplot
        ax4.boxplot(self.df)
        ax4.set_xlabel('X axis')
        ax4.set_ylabel('Y axis')
        ax4.set_title('Box Plot')
        legend = ax4.legend(self.df,fontsize="8")
        legend.set_draggable(True)

        # adjust spacing between subplots
        self.canv.figure.subplots_adjust(hspace=0.5, wspace=0.3)

        self.canv.draw()

        
        
    def getFile(self):
        """ This function will get the address of the csv file location also calls a readData function"""
        self.filename = QFileDialog.getOpenFileName(filter = "csv (*.csv)")[0]
        print("File :", self.filename)
        self.readData()
        
    def readData(self):
        """ This function will read the data using pandas and call the update
            function to plot
        """
        import os
        base_name = os.path.basename(self.filename)
        self.Title = os.path.splitext(base_name)[0]
        print('FILE',self.Title )
        self.df = pd.read_csv(self.filename,encoding = 'utf-8').fillna(0)
        self.df = self.df[:300]
        self.Update(self.themes[0]) # lets 0th theme be the default : bmh


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Remote Patient Monitoring System"))
        self.pushButton.setText(_translate("MainWindow", "IMPORT"))
        self.pushButton_4.setText(_translate("MainWindow", "EXIT"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_CSV.setText(_translate("MainWindow", "Open CSV"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
import bgg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
